export enum ConfigEnum {
  DB_TYPE = 'DB_TYPE',
  DB_PORT = 'DB_PORT',
  DB_HOST = 'DB_HOST',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_SYNC = 'DB_SYNC',
  DB_DATABASE = 'DB_DATABASE',
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_ON = 'LOG_ON'
}
